#Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.daemon.jvmargs=-Xmx3072M
#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Maven Publishing
GROUP=io.github.woods-marshes
VERSION_NAME=0.1.0-SNAPSHOT
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/woods-marshes/prosemirror-compose
POM_LICENSE_NAME=Apache License 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/woods-marshes/prosemirror-compose
POM_SCM_CONNECTION=scm:git:git://github.com/woods-marshes/prosemirror-compose.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/woods-marshes/prosemirror-compose.git
POM_DEVELOPER_ID=woods-marshes
POM_DEVELOPER_NAME=woods-marshes
POM_DEVELOPER_URL=https://github.com/woods-marshes
#Vanniktech Maven Central Publishing
mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true
